version: "3.9"

services:

  worker:

    build: .

    environment:

      API_KEY: $API_KEY

      API_HASH: $API_HASH

      STRING_SESSION: $STRING_SESSION

      BOT_TOKEN: $BOT_TOKEN

      BOT_USERNAME: $BOT_USERNAME

      BOTLOG_CHATID: $BOTLOG_CHATID
