# Ayiin - Userbot
# Credits (C) 2022-2023 @AyiinXd
#
# FROM Ayiin-Userbot <https://github.com/AyiinXd/Ayiin-Userbot>
# t.me/AyiinXdSupport & t.me/AyiinSupport

# ========================×========================
#                Link For Collaborator
# ========================×========================


# ========================Asupan Sagapung========================


asupan_sagapung = [
    f"https://t.me/AsupanSagapungRobot?start={asu}"
    for asu in [
        "Z2V0LTUwMDg1MDA5NjYyMDU",
        "Z2V0LTYwMTAyMDExNTk0NDY",
        "Z2V0LTcwMTE5MDEzNTI2ODc",
        "Z2V0LTkwMTUzMDE3MzkxNjk",
        "Z2V0LTgwMTM2MDE1NDU5Mjg",
        "Z2V0LTEwMDE3MDAxOTMyNDEw",
        "Z2V0LTExMDE4NzAyMTI1NjUx",
        "Z2V0LTEyMDIwNDAyMzE4ODky",
        "Z2V0LTEzMDIyMTAyNTEyMTMz",
        "Z2V0LTE1MDI1NTAyODk4NjE1",
        "Z2V0LTE0MDIzODAyNzA1Mzc0",
        "Z2V0LTE2MDI3MjAzMDkxODU2",
        "Z2V0LTE3MDI4OTAzMjg1MDk3",
        "Z2V0LTE4MDMwNjAzNDc4MzM4",
        "Z2V0LTIwMDM0MDAzODY0ODIw",
        "Z2V0LTE5MDMyMzAzNjcxNTc5",
    ]
]


# ========================Exolink========================


exolink = [
    "https://t.me/asupanexorBot?start=Z2V0LTI1MDQ0MDg4ODg4MTc1",
    "https://t.me/asupanexorBot?start=Z2V0LTI2MDQ1ODUyNDQzNzAy",
    "https://t.me/asupanexorBot?start=Z2V0LTI4MDQ5Mzc5NTU0NzU2",
    "https://t.me/asupanexorBot?start=Z2V0LTMwMDUyOTA2NjY1ODEw",
    "https://t.me/asupanexorBot?start=Z2V0LTMxMDU0NjcwMjIxMzM3",
    "https://t.me/asupanexorBot?start=Z2V0LTMzMDU4MTk3MzMyMzkx",
    "https://t.me/asupanexorBot?start=Z2V0LTMyMDU2NDMzNzc2ODY0",
    "https://t.me/asupanexorBot?start=Z2V0LTM0MDU5OTYwODg3OTE4",
    "https://t.me/asupanexorBot?start=Z2V0LTM1MDYxNzI0NDQzNDQ1",
    "https://t.me/asupanexorBot?start=Z2V0LTQyMDc0MDY5MzMyMTM0",
    "https://t.me/asupanexorBot?start=Z2V0LTM5MDY4Nzc4NjY1NTUz",
    "https://t.me/asupanexorBot?start=Z2V0LTQxMDcyMzA1Nzc2NjA3",
    "https://t.me/asupanexorBot?start=Z2V0LTQwMDcwNTQyMjIxMDgw",
    "https://t.me/asupanexorBot?start=Z2V0LTQzMDc1ODMyODg3NjYx",
    "https://t.me/asupanexorBot?start=Z2V0LTQ0MDc3NTk2NDQzMTg4",
    "https://t.me/asupanexorBot?start=Z2V0LTQ1MDc5MzU5OTk4NzE1",
    "https://t.me/asupanexorBot?start=Z2V0LTQ2MDgxMTIzNTU0MjQy",
    "https://t.me/asupanexorBot?start=Z2V0LTQ3MDgyODg3MTA5NzY5",
    "https://t.me/asupanexorBot?start=Z2V0LTQ5MDg2NDE0MjIwODIz",
    "https://t.me/asupanexorBot?start=Z2V0LTQ4MDg0NjUwNjY1Mjk2",
    "https://t.me/asupanexorBot?start=Z2V0LTU1MDk2OTk1NTUzOTg1",
    "https://t.me/asupanexorBot?start=Z2V0LTU0MDk1MjMxOTk4NDU4",
    "https://t.me/asupanexorBot?start=Z2V0LTUxMDg5OTQxMzMxODc3",
    "https://t.me/asupanexorBot?start=Z2V0LTUwMDg4MTc3Nzc2MzUw",
    "https://t.me/asupanexorBot?start=Z2V0LTUyMDkxNzA0ODg3NDA0",
    "https://t.me/asupanexorBot?start=Z2V0LTUzMDkzNDY4NDQyOTMx",
    "https://t.me/asupanexorBot?start=Z2V0LTU2MDk4NzU5MTA5NTEy",
    "https://t.me/asupanexorBot?start=Z2V0LTYxMTA3NTc2ODg3MTQ3",
    "https://t.me/asupanexorBot?start=Z2V0LTU3MTAwNTIyNjY1MDM5",
    "https://t.me/asupanexorBot?start=Z2V0LTU4MTAyMjg2MjIwNTY2",
    "https://t.me/asupanexorBot?start=Z2V0LTU5MTA0MDQ5Nzc2MDkz",
    "https://t.me/asupanexorBot?start=Z2V0LTYwMTA1ODEzMzMxNjIw",
    "https://t.me/asupanexorBot?start=Z2V0LTY1MTE0NjMxMTA5MjU1",
    "https://t.me/asupanexorBot?start=Z2V0LTY0MTEyODY3NTUzNzI4",
    "https://t.me/asupanexorBot?start=Z2V0LTYyMTA5MzQwNDQyNjc0",
    "https://t.me/asupanexorBot?start=Z2V0LTYzMTExMTAzOTk4MjAx",
    "https://t.me/asupanexorBot?start=Z2V0LTY2MTE2Mzk0NjY0Nzgy",
    "https://t.me/asupanexorBot?start=Z2V0LTY3MTE4MTU4MjIwMzA5",
    "https://t.me/asupanexorBot?start=Z2V0LTY4MTE5OTIxNzc1ODM2",
    "https://t.me/asupanexorBot?start=Z2V0LTcyMTI2OTc1OTk3OTQ0",
    "https://t.me/asupanexorBot?start=Z2V0LTcwMTIzNDQ4ODg2ODkw",
    "https://t.me/asupanexorBot?start=Z2V0LTY5MTIxNjg1MzMxMzYz",
    "https://t.me/asupanexorBot?start=Z2V0LTcxMTI1MjEyNDQyNDE3",
    "https://t.me/asupanexorBot?start=Z2V0LTc3MTM1NzkzNzc1NTc5",
    "https://t.me/asupanexorBot?start=Z2V0LTczMTI4NzM5NTUzNDcx",
    "https://t.me/asupanexorBot?start=Z2V0LTc0MTMwNTAzMTA4OTk4",
    "https://t.me/asupanexorBot?start=Z2V0LTc4MTM3NTU3MzMxMTA2",
    "https://t.me/asupanexorBot?start=Z2V0LTc1MTMyMjY2NjY0NTI1",
    "https://t.me/asupanexorBot?start=Z2V0LTc2MTM0MDMwMjIwMDUy",
    "https://t.me/asupanexorBot?start=Z2V0LTc5MTM5MzIwODg2NjMz",
    "https://t.me/asupanexorBot?start=Z2V0LTgxMTQyODQ3OTk3Njg3",
    "https://t.me/asupanexorBot?start=Z2V0LTgyMTQ0NjExNTUzMjE0",
    "https://t.me/asupanexorBot?start=Z2V0LTgwMTQxMDg0NDQyMTYw",
    "https://t.me/asupanexorBot?start=Z2V0LTgzMTQ2Mzc1MTA4NzQx",
    "https://t.me/asupanexorBot?start=Z2V0LTg4MTU1MTkyODg2Mzc2",
    "https://t.me/asupanexorBot?start=Z2V0LTg2MTUxNjY1Nzc1MzIy",
    "https://t.me/asupanexorBot?start=Z2V0LTg3MTUzNDI5MzMwODQ5",
    "https://t.me/asupanexorBot?start=Z2V0LTg0MTQ4MTM4NjY0MjY4",
    "https://t.me/asupanexorBot?start=Z2V0LTg1MTQ5OTAyMjE5Nzk1",
    "https://t.me/asupanexorBot?start=Z2V0LTg5MTU2OTU2NDQxOTAz",
    "https://t.me/asupanexorBot?start=Z2V0LTkwMTU4NzE5OTk3NDMw",
    "https://t.me/asupanexorBot?start=Z2V0LTkzMTY0MDEwNjY0MDEx",
    "https://t.me/asupanexorBot?start=Z2V0LTk0MTY1Nzc0MjE5NTM4",
    "https://t.me/asupanexorBot?start=Z2V0LTkxMTYwNDgzNTUyOTU3",
    "https://t.me/asupanexorBot?start=Z2V0LTkyMTYyMjQ3MTA4NDg0",
    "https://t.me/asupanexorBot?start=Z2V0LTk2MTY5MzAxMzMwNTky",
    "https://t.me/asupanexorBot?start=Z2V0LTk4MTcyODI4NDQxNjQ2",
    "https://t.me/asupanexorBot?start=Z2V0LTk1MTY3NTM3Nzc1MDY1",
    "https://t.me/asupanexorBot?start=Z2V0LTk3MTcxMDY0ODg2MTE5",
    "https://t.me/asupanexorBot?start=Z2V0LTk5MTc0NTkxOTk3MTcz",
    "https://t.me/asupanexorBot?start=Z2V0LTEwMDE3NjM1NTU1MjcwMA",
    "https://t.me/asupanexorBot?start=Z2V0LTEwMTE3ODExOTEwODIyNw",
    "https://t.me/asupanexorBot?start=Z2V0LTEwMjE3OTg4MjY2Mzc1NA",
    "https://t.me/asupanexorBot?start=Z2V0LTEwNTE4NTE3MzMzMDMzNQ",
    "https://t.me/asupanexorBot?start=Z2V0LTEwMzE4MTY0NjIxOTI4MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTEwNDE4MzQwOTc3NDgwOA",
    "https://t.me/asupanexorBot?start=Z2V0LTEwNjE4NjkzNjg4NTg2Mg",
    "https://t.me/asupanexorBot?start=Z2V0LTEwNzE4ODcwMDQ0MTM4OQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE1MDI2NDUzMzMyOTA1MA",
    "https://t.me/asupanexorBot?start=Z2V0LTE0OTI2Mjc2OTc3MzUyMw",
    "https://t.me/asupanexorBot?start=Z2V0LTE1MzI2OTgyMzk5NTYzMQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE1MTI2NjI5Njg4NDU3Nw",
    "https://t.me/asupanexorBot?start=Z2V0LTE1MjI2ODA2MDQ0MDEwNA",
    "https://t.me/asupanexorBot?start=Z2V0LTE1NjI3NTExNDY2MjIxMg",
    "https://t.me/asupanexorBot?start=Z2V0LTE1NTI3MzM1MTEwNjY4NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE1NzI3Njg3ODIxNzczOQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE1NDI3MTU4NzU1MTE1OA",
    "https://t.me/asupanexorBot?start=Z2V0LTE1OTI4MDQwNTMyODc5Mw"
    "https://t.me/asupanexorBot?start=Z2V0LTE1ODI3ODY0MTc3MzI2Ng",
    "https://t.me/asupanexorBot?start=Z2V0LTE2MDI4MjE2ODg4NDMyMA",
    "https://t.me/asupanexorBot?start=Z2V0LTE2MTI4MzkzMjQzOTg0Nw",
    "https://t.me/asupanexorBot?start=Z2V0LTE2MjI4NTY5NTk5NTM3NA",
    "https://t.me/asupanexorBot?start=Z2V0LTE2NTI5MDk4NjY2MTk1NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE2NDI4OTIyMzEwNjQyOA",
    "https://t.me/asupanexorBot?start=Z2V0LTE2ODI5NjI3NzMyODUzNg",
    "https://t.me/asupanexorBot?start=Z2V0LTE3MTMwMTU2Nzk5NTExNw",
    "https://t.me/asupanexorBot?start=Z2V0LTE2OTI5ODA0MDg4NDA2Mw",
    "https://t.me/asupanexorBot?start=Z2V0LTE3MzMwNTA5NTEwNjE3MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE3NTMwODYyMjIxNzIyNQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE4MTMxOTIwMzU1MDM4Nw",
    "https://t.me/asupanexorBot?start=Z2V0LTE4MDMxNzQzOTk5NDg2MA",
    "https://t.me/asupanexorBot?start=Z2V0LTE3NzMxMjE0OTMyODI3OQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE4NTMyNjI1Nzc3MjQ5NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE4MzMyMjczMDY2MTQ0MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE5MzM0MDM2NjIxNjcxMQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE5ODM0OTE4Mzk5NDM0Ng",
    "https://t.me/asupanexorBot?start=Z2V0LTE4ODMzMTU0ODQzOTA3Ng",
    "https://t.me/asupanexorBot?start=Z2V0LTE4OTMzMzMxMTk5NDYwMw",
    "https://t.me/asupanexorBot?start=Z2V0LTE5NTM0Mzg5MzMyNzc2NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE5NzM0NzQyMDQzODgxOQ",
    "https://t.me/asupanexorBot?start=Z2V0LTE5OTM1MDk0NzU0OTg3Mw",
    "https://t.me/asupanexorBot?start=Z2V0LTIwODM2NjgxOTU0OTYxNg",
    "https://t.me/asupanexorBot?start=Z2V0LTIwMzM1ODAwMTc3MTk4MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIxMjM3Mzg3Mzc3MTcyNA",
    "https://t.me/asupanexorBot?start=Z2V0LTIwMjM1NjIzODIxNjQ1NA",
    "https://t.me/asupanexorBot?start=Z2V0LTIwNTM2MTUyODg4MzAzNQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIwOTM2ODU4MzEwNTE0Mw",
    "https://t.me/asupanexorBot?start=Z2V0LTIxNjM4MDkyNzk5MzgzMg",
    "https://t.me/asupanexorBot?start=Z2V0LTIxNDM3NzQwMDg4Mjc3OA",
    "https://t.me/asupanexorBot?start=Z2V0LTIxNzM4MjY5MTU0OTM1OQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIxMzM3NTYzNzMyNzI1MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIyMDM4Nzk4MjIxNTk0MA",
    "https://t.me/asupanexorBot?start=Z2V0LTIyMzM5MzI3Mjg4MjUyMQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIyNjM5ODU2MzU0OTEwMg",
    "https://t.me/asupanexorBot?start=Z2V0LTIyNTM5Njc5OTk5MzU3NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIzNDQxMjY3MTk5MzMxOA",
    "https://t.me/asupanexorBot?start=Z2V0LTIzMDQwNTYxNzc3MTIxMA",
    "https://t.me/asupanexorBot?start=Z2V0LTIzODQxOTcyNjIxNTQyNg",
    "https://t.me/asupanexorBot?start=Z2V0LTIzNTQxNDQzNTU0ODg0NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTIzNjQxNjE5OTEwNDM3Mg",
    "https://t.me/asupanexorBot?start=Z2V0LTI0NDQzMDMwNzU0ODU4OA",
    "https://t.me/asupanexorBot?start=Z2V0LTI0MzQyODU0Mzk5MzA2MQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI0MTQyNTAxNjg4MjAwNw",
    "https://t.me/asupanexorBot?start=Z2V0LTIzOTQyMTQ4OTc3MDk1Mw",
    "https://t.me/asupanexorBot?start=Z2V0LTI0NjQzMzgzNDY1OTY0Mg",
    "https://t.me/asupanexorBot?start=Z2V0LTI0NzQzNTU5ODIxNTE2OQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI0ODQzNzM2MTc3MDY5Ng",
    "https://t.me/asupanexorBot?start=Z2V0LTI1MzQ0NjE3OTU0ODMzMQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI1NTQ0OTcwNjY1OTM4NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI1MjQ0NDQxNTk5MjgwNA",
    "https://t.me/asupanexorBot?start=Z2V0LTI2MDQ1ODUyNDQzNzAyMA",
    "https://t.me/asupanexorBot?start=Z2V0LTI1OTQ1Njc2MDg4MTQ5Mw",
    "https://t.me/asupanexorBot?start=Z2V0LTI2MjQ2MjA1MTU0ODA3NA",
    "https://t.me/asupanexorBot?start=Z2V0LTI2NzQ3MDg2OTMyNTcwOQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI2NTQ2NzM0MjIxNDY1NQ",
    "https://t.me/asupanexorBot?start=Z2V0LTI3NDQ4MzIxNDIxNDM5OA"
]


# ========================×========================
#                Link For Collaborator
# ========================×========================
