Truth = (
    "Apakah kamu pernah menghantui seseorang?",
    "Pernahkah kamu mendatangi orang tuamu dan mengajak orang tuamu ngewe?",
    "Siapa orang terakhir yang paling kamu sukai? Dan Mengapa?",
    "Apakah Anda pernah diskors dari sekolah??",
    "Jika Anda harus memilih antara telanjang atau pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang, mana yang akan Anda pilih?",
    "Apa satu hal yang kamu takuti?",
    "Apakah kamu menyukai seseorang saat ini??",
    "Satu hal tentang sahabatmu yang membuatmu iri?",
    "Apakah Anda pernah berbohong ke pacar Anda untuk pria yang kaya?",
    "Berapa ukuran bh Anda??",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan apa alasannya?",
    "Deskripsikan pasangan ideal Anda.",
    "Hal apa yang paling menakutkan yang pernah kamu lakukan?",
    "Pernahkah Anda mengupil dan memakannya?",
    "Pernahkah Anda berbohong tentang usia Anda untuk berpartisipasi dalam kontes?",
    "Pernahkah Anda pernah ketahuan saat sedang memeriksa seseorang?",
    "Pernahkah Anda ketahuan saat sedang ngewe dengan pacar anda?",
    "Pernahkah Anda ketahuan saat sedang coli ?",
    "Pernahkah Anda Ketahuan saat sedang clmk ?",
    "Apakah Anda Sudah Coli Hari ini ?",
    "Apakah Anda Sudah Clmk Hari ini ?",
    "Pernahkah Anda Menyepong Kntl ?",
    "Pernahkah Anda Menjilati Memek ?",
)

Dare = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tunjukkan lima orang terakhir yang Anda Chat dan apa isi pesannya",
    "Biarkan anggota grup lainnya Mengirim Pesan ke seseorang dari akun Instagram Anda",
    "Makanlah bawang putih mentah",
    "Lakukan 100× Push-up",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di dekatmu. Hanya kepada temanmu bukan KELUARGAMU!",
    "Berikan pijatan kaki kepada orang di Dekat Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat item pakaian dan berkeliling di halaman rumah",
    "Sukai 15 posting pertama di umpan berita Facebook Anda",
    "Makan satu sendok Merica",
    "Tutup matamu sampai kamu pergi lagi",
    "Kirim pesan ke orang terakhir di kontak telepon Anda",
    "Pamerkan wajah sange Anda",
    "Jilati buah pisang sampai membuat seseorang sange",
    "Kosongkan dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan gerakan seksi terbaikmu",
    "Berpura-pura menjadi orang di dekat Anda selama 10 menit",
    "Memakan camilan tanpa menggunakan tangan anda",
    "Katakan dua hal jujur ​​​​tentang semua orang dalam grup",
    "Remas tete selama 10 menit",
    "Remas kntl selama 10 menit",
    "Cobalah dan buat grup tertawa secepat mungkin",
    "Cobalah untuk memasukkan seluruh kepalan tangan Anda ke dalam mulut Anda",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu sendiri",
    "Coba jilat sikumu",
    "Posting selfie terlama di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Tarian tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan camilan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar pesan Telegram Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk WhatsApp Anda",
    "Kirim tangkapan layar, layar beranda Anda.",
    "Kirim cover lagu favoritmu. 🎤",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Menyatakan cinta kepada 10 orang di grup saat ini. ❤️",
    "Beritahu siapa cinta sejatimu.",
    "Jadikan foto gebetanmu sebagai foto profil.",
    "Sarankan saya lebih berani.",
    "Tunjukan Video Bokp Anda Ke Anggota Grup",
)
